# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"

# Site Settings
locale: "zh-CN"
rtl                      : # true, false (default) # turns direction of the page into right to left for RTL languages
title: "Sunset的博客"
title_separator: "-"
subtitle: "Placeholder. 您可能没有启用JavaScript。" # site tagline that appears below site title in masthead # 也可以当作slogan
name: "Sunset"
description: "Sunset的博客"
url: https://blog.sunmkt.top # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: / # the subpath of your site, e.g. "/blog"
repository: SunsetMkt/Blog-jekyll # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser: "/assets/images/500x300.png" # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo: "/assets/images/apple-touch-icon.png" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title: # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs: true # true, false (default)
words_per_minute: 200
enable_copy_code_button: true # true, false (default)
copyright: # "copyright" name, defaults to site.title
copyright_url: # "copyright" URL, defaults to site.url
comments:
  provider: "giscus" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname: # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server: # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid:
    num_posts: # 5 (default)
    colorscheme: # "light" (default), "dark"
  utterances:
    theme: # "github-light" (default), "github-dark"
    issue_term: # "pathname" (default)
  giscus:
    repo_id: "R_kgDOG1y38g" # Shown during giscus setup at https://giscus.app
    category_name: "Announcements" # Full text name of the category
    category_id: "DIC_kwDOG1y38s4CgWyv" # Shown during giscus setup at https://giscus.app
    discussion_term: "pathname" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled: "1" # '1' for enabled (default), '0' for disabled
    theme: "preferred_color_scheme" # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
    strict: "0" # 1 for enabled, 0 for disabled (default)
    input_position: "top" # "top", "bottom" # The comment input box will be placed above or below the comments
    emit_metadata: "1" # 1 for enabled, 0 for disabled (default) # https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#imetadatamessage
    lang: "zh-CN" # "en" (default)
    lazy: true # true, false # Loading of the comments will be deferred until the user scrolls near the comments container.
  staticman:
    branch: # "master"
    endpoint: # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey:
  secret:
atom_feed:
  path: # blank (default) uses feed.xml
  hide: # true, false (default)
search: true # true, false (default)
search_full_content: false # true, false (default)
search_provider: lunr # lunr (default), algolia, google
lunr:
  search_within_pages: true # true, false (default)
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false
google:
  search_engine_id: # YOUR_SEARCH_ENGINE_ID
  instant_search: # false (default), true
# SEO Related
google_site_verification: # Done with DNS record
bing_site_verification: # Done with Google
naver_site_verification:
yandex_site_verification: # Done
baidu_site_verification:

# Social Sharing
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image: "/assets/images/sunset2_compressed.jpg" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: # Person or Organization (defaults to Person)
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider: # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id:
    anonymize_ip: # true, false (default)

# Site Author
author:
  name: "Sunset"
  avatar: "/assets/images/sunset2_compressed.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: "Lead Programmer of Sunset Edu. & Tech. Group."
  location: "Unknown"
  email: "hi@sunmkt.top"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: # mailto:hi@sunmkt.top
      # url: mailto:your.name@email.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: # "https://sunmkt.top"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SunsetMkt"
      # url: "https://github.com/"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url:
    - label: "Discord服务器"
      icon: "fab fa-fw fa-discord"
      url:

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SunsetMkt"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: # "https://gitlab.com/SunsetMkt"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: Asia/Singapore # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Pagination with jekyll-paginate
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Pagination with jekyll-paginate-v2
# See https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
#   for configuration details
pagination:
  # Set enabled to true to use paginate v2
  # enabled: true
  debug: false
  collection: "posts"
  per_page: 10
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after: 2

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-git-hash
  - jekyll-webp
  - jekyll-loading-lazy
  - liquid-md5
  - jekyll-redirect-from
  - jekyll-target-blank
  - jekyll_random_hex

# mimic GitHub Pages with --safe
# No need to keep this in further versions since GitHub has removed
# the default "safe" Jekyll build environment and turn to Actions since 2024.6
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: true
      read_time: true # true
      comments: true # true
      share: true # true
      related: false # true
      toc: true # false # To show Table of Content (aka. menu)

# head_scripts:
#   - https://

after_footer_scripts:
  # - https://unpkg.com/toastr@2.1.4/build/toastr.min.js
  - /assets/js/utils.js
  # - /assets/js/custom-script-loads-after-footer.js

############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
# https://github.com/sverrirs/jekyll-webp
webp:
  enabled: false

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/assets/"]

  # Whether to search in nested directories or not
  nested: true

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff", ".gif"]

  # File extensions for animated gif files
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  # Eg : "/usr/local/bin/cwebp"
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: true
############################################################
