name: google-indexing-script

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [$default-branch, main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  google-indexing-script:
    runs-on: ubuntu-latest
    steps:
      - name: Google Indexing Script
        run: |
          npm i -g google-indexing-script
          gis -v
          echo ${{ secrets.GIS_AUTH_JSON_B64 }} | base64 --decode > service_account.json
          mkdir ~/.gis
          mv service_account.json ~/.gis
          gis blog.sunmkt.top --rpm-retry
